### ISSUE TITLE
Criar o README.md

### ISSUE THREAD

**Issue by armando-couto** [andre-dan/Torre-de-Hanoi#1]
No arquivo deverá ter todas as explicações:

- Para que serve esse algoritmo.
- Como podemos rodar.

**Comment by andre-dan** [comment]
Olá Armando, segue o link com as informações
https://github.com/andre-dan/Torre-de-Hanoi/blob/master/README.md
Agradeço desde já

Em sáb., 11 de abr. de 2020 às 00:34, Antonio Armando Couto Bem Filho <
notifications@github.com> escreveu:
